project:
  type: website
  output-dir: docs
  
website:
  title: "1MS071"
  navbar:
    left:
      - href: Statistik.qmd
        text: Home
      
format:
  html: 
    toc: true
    toc-depth: 3
    number-sections: true
    theme: cosmo       # Bootstrap theme (cosmo, minty, journal, etc.)