<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1MS900 - Komplement till Slides i Statistik</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">1MS900</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./Bayes.qmd">
 <span class="menu-text">Home</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#föreläsning-3" id="toc-föreläsning-3" class="nav-link active" data-scroll-target="#föreläsning-3"><span class="toc-section-number">1</span>  Föreläsning 3</a>
  <ul class="collapse">
  <li><a href="#ju-starkare-effekten-är-desto-större-blir-testets-styrka" id="toc-ju-starkare-effekten-är-desto-större-blir-testets-styrka" class="nav-link" data-scroll-target="#ju-starkare-effekten-är-desto-större-blir-testets-styrka"><span class="toc-section-number">1.1</span>  Ju starkare effekten är, desto större blir testets styrka</a></li>
  </ul></li>
  <li><a href="#föreläsning-4" id="toc-föreläsning-4" class="nav-link" data-scroll-target="#föreläsning-4"><span class="toc-section-number">2</span>  Föreläsning 4</a>
  <ul class="collapse">
  <li><a href="#h0-mu-3800-textgram-mot-h1-mu-neq-3800-textgram" id="toc-h0-mu-3800-textgram-mot-h1-mu-neq-3800-textgram" class="nav-link" data-scroll-target="#h0-mu-3800-textgram-mot-h1-mu-neq-3800-textgram"><span class="toc-section-number">2.1</span>  H0: <span class="math inline">\(\mu = 3800 \text{gram}\)</span> mot H1: <span class="math inline">\(\mu \neq 3800 \text{gram}\)</span></a></li>
  <li><a href="#h0-mu-leq-3800-textgram-mot-h1-mu-3800-textgram" id="toc-h0-mu-leq-3800-textgram-mot-h1-mu-3800-textgram" class="nav-link" data-scroll-target="#h0-mu-leq-3800-textgram-mot-h1-mu-3800-textgram"><span class="toc-section-number">2.2</span>  H0: <span class="math inline">\(\mu \leq 3800 \text{gram}\)</span> mot H1: <span class="math inline">\(\mu &gt; 3800 \text{gram}\)</span></a></li>
  <li><a href="#h0-mu-geq-3800-textgram-mot-h1-mu-3800-textgram" id="toc-h0-mu-geq-3800-textgram-mot-h1-mu-3800-textgram" class="nav-link" data-scroll-target="#h0-mu-geq-3800-textgram-mot-h1-mu-3800-textgram"><span class="toc-section-number">2.3</span>  H0: <span class="math inline">\(\mu \geq 3800 \text{gram}\)</span> mot H1: <span class="math inline">\(\mu &lt; 3800 \text{gram}\)</span></a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Komplement till Slides i Statistik</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="föreläsning-3" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Föreläsning 3</h1>
<section id="ju-starkare-effekten-är-desto-större-blir-testets-styrka" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="ju-starkare-effekten-är-desto-större-blir-testets-styrka"><span class="header-section-number">1.1</span> Ju starkare effekten är, desto större blir testets styrka</h2>
<p>Det står på sidan 23 av sliden till föreläsning 3 att ju starkare effekten är, desto större blir testets styrka. Om vi testar <span class="math display">\[\begin{eqnarray*}
\text{H0: det finns ingen skillnad}
\end{eqnarray*}\]</span> innebär det att strykan är större om skillnaden är större. Vi kan genomföra en simuleringsstudie för att bevisa detta. Till exempel, jag vill testar <span class="math display">\[\begin{eqnarray*}
\text{H0: det finns ingen skillnad mellan väntevärdena av två oberoende grupper}
\end{eqnarray*}\]</span> mot <span class="math display">\[\begin{eqnarray*}
\text{H1: det finns en skillnad mellan väntevärdena.}
\end{eqnarray*}\]</span> Jag simulerar <span class="math inline">\(n=100\)</span> observationer från slumpvariabeln <span class="math inline">\(X \sim N(0, 1)\)</span> och <span class="math inline">\(n=100\)</span> observationer från slumpvariabeln <span class="math inline">\(Y \sim N(\mu, 1)\)</span>. Skillnaden i väntevärde mellan grupperna är <span class="math display">\[\begin{eqnarray*}
\text{E}(X) - \text{E}(Y) &amp; = &amp; -\mu.
\end{eqnarray*}\]</span> T-testet kan används för att testa skillnaden. Jag jämför p-värdet med signifikansnivå 0.05. Jag kan upprepa simuleringen <span class="math inline">\(10 000\)</span> gånger. Resultatet sparas i vektorn <code>Signifikant</code>. Om <span class="math inline">\(\text{Signifikant[i]}=1\)</span> innebär att den i:e simuleringen ledar till ett signifikant resultat (p-värdet &lt; 0.05). Annars <span class="math inline">\(\text{Signifikant[i]}=0\)</span>.</p>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>Mu <span class="ot">&lt;-</span> <span class="fl">0.1</span> <span class="co"># Väntevärdet av Y</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>Signifikant <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">10000</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span> <span class="sc">:</span> <span class="dv">10000</span>){</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Simulera X och Y</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    X <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">100</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    Y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">100</span>, <span class="at">mean =</span> Mu, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Genomföra t test </span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(X, Y)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Obtain p-value</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    Pvalue <span class="ot">&lt;-</span> test<span class="sc">$</span>p.value</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Jämföra p-värdet med signifikansnivå 0.05</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    Signifikant[i] <span class="ot">&lt;-</span> (Pvalue <span class="sc">&lt;=</span> <span class="fl">0.05</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Styrkan hos ett statistiskt hypotestest är sannolikheten att förkasta H0 om H1 är sann. I exempelet ovan är H1 sann eftersom <span class="math inline">\(\mu = 0.1\)</span>, alltså det finns en skillnad mellan grupperna. Vi kan därför uppskatta styrkan genom <code>mean(Signifikant)</code>, dvs andelen signifikanta resultat i vår simulering:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(Signifikant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1072</code></pre>
</div>
</div>
<p>Nu ökar jag <span class="math inline">\(\mu=0.1\)</span> till <span class="math inline">\(\mu=0.25\)</span> och genomför simuleringen igen.</p>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>Mu <span class="ot">&lt;-</span> <span class="fl">0.25</span> <span class="co"># Väntevärdet av Y</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>Signifikant <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">10000</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span> <span class="sc">:</span> <span class="dv">10000</span>){</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Simulera X och Y</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    X <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">100</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    Y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">100</span>, <span class="at">mean =</span> Mu, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Genomföra t test </span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(X, Y)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Obtain p-value</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    Pvalue <span class="ot">&lt;-</span> test<span class="sc">$</span>p.value</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Jämföra p-värdet med signifikansnivå 0.05</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    Signifikant[i] <span class="ot">&lt;-</span> (Pvalue <span class="sc">&lt;=</span> <span class="fl">0.05</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Skattningen av strykan blir</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(Signifikant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4247</code></pre>
</div>
</div>
<p>vilket är större än strykan när <span class="math inline">\(\mu = 0.1\)</span>.</p>
<p>Om jag ökar <span class="math inline">\(\mu=\)</span> till <span class="math inline">\(\mu=1\)</span> skulle jag får en ännu större styrka. Vi kan kolla om det stämmer.</p>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Mu <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="co"># Väntevärdet av Y</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>Signifikant <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">10000</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span> <span class="sc">:</span> <span class="dv">10000</span>){</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Simulera X och Y</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    X <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">100</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    Y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">100</span>, <span class="at">mean =</span> Mu, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Genomföra t test </span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(X, Y)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Obtain p-value</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    Pvalue <span class="ot">&lt;-</span> test<span class="sc">$</span>p.value</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="do">## Jämföra p-värdet med signifikansnivå 0.05</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    Signifikant[i] <span class="ot">&lt;-</span> (Pvalue <span class="sc">&lt;=</span> <span class="fl">0.05</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Skattningen av strykan blir</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(Signifikant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Vi kan nästan alltid upptäcka en skillnad mellan grupperna!</p>
</section>
</section>
<section id="föreläsning-4" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Föreläsning 4</h1>
<p>Jag kommer att förklara hur man beräknar p-värdet för t-testet här. Ta vikten hos adeliepinviner som exempel.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>Adelie <span class="ot">&lt;-</span> <span class="fu">subset</span>(penguins, species <span class="sc">==</span> <span class="st">"Adelie"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>vikt <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(Adelie<span class="sc">$</span>body_mass_g)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Anta att signifikansnivån är <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<section id="h0-mu-3800-textgram-mot-h1-mu-neq-3800-textgram" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="h0-mu-3800-textgram-mot-h1-mu-neq-3800-textgram"><span class="header-section-number">2.1</span> H0: <span class="math inline">\(\mu = 3800 \text{gram}\)</span> mot H1: <span class="math inline">\(\mu \neq 3800 \text{gram}\)</span></h2>
<p>Vi börjar med att testa H0: <span class="math inline">\(\mu = 3800 \text{gram}\)</span> mot H1: <span class="math inline">\(\mu \neq 3800 \text{gram}\)</span>. Den standardiserade differensen mellan medelvikt och 3800 gram är <span class="math display">\[\begin{eqnarray}
t &amp; = &amp; \frac{\bar{x} - 3800}{s / \sqrt{n}},
\end{eqnarray}\]</span> där <span class="math inline">\(\bar{x}\)</span> är medelvikt som vi beräknar från data, och <span class="math inline">\(s / \sqrt{n}\)</span> är standardfel. Sådan standardiserad differens mäter skillnaden mellan data och vår H0.</p>
<ul>
<li>Om <span class="math inline">\(t\)</span> är mycket större än 0 innebär att vår data tyder på att medelvikten är större än H0.</li>
<li>Om <span class="math inline">\(t\)</span> är mycket mindre än 0 innebär att vår data tyder på att medelvikten är mindre än H0.</li>
</ul>
<p>När vi använder <code>t.test()</code> för att testa H0 mot H1 ovan får vi resultatet</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(vikt, <span class="at">mu =</span> <span class="dv">3800</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  vikt
t = -2.662, df = 150, p-value = 0.008616
alternative hypothesis: true mean is not equal to 3800
95 percent confidence interval:
 3626.926 3774.398
sample estimates:
mean of x 
 3700.662 </code></pre>
</div>
</div>
<p><span class="math inline">\(t = -2.662\)</span> är den standardiserade skillnaden som vi kan beräkna från vår data. Vi måste bestämma om detta t-värde avviker tillräckligt från H0. Om data är normalfördelade och H0 stämmer följer <span class="math inline">\(t\)</span> en t-fördelning med frihetsgrader <span class="math inline">\(n - 1\)</span>. Det betyder att <span class="math inline">\(100(1 - \alpha)%\)</span> av alla studier skulle ge <span class="math inline">\(-t_{\alpha/2}^{(n-1)} &lt; t &lt; t_{\alpha/2}^{(n-1)}\)</span> om vi kan upprepa samma studie många gånger. I vårt exempel är frihetsgraderna 150 (eftersom vi har <span class="math inline">\(151\)</span> observationer) och <span class="math inline">\(t_{\alpha/2}^{(n-1)} = 1.975799\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="at">p =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.05</span> <span class="sc">/</span> <span class="dv">2</span>, <span class="at">df =</span> <span class="dv">151</span> <span class="sc">-</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.975905</code></pre>
</div>
</div>
<p>Det innebär att ett t-värde som ligger mellan <span class="math inline">\(-1.975905\)</span> och <span class="math inline">\(1.975905\)</span> anses vara helt “normalt” om H0 är sann. Om t-värdet ligger utanför <span class="math inline">\((-1.975905, 1.975905)\)</span> anses vår data “konstiga” under H0. Det vill säga, om absolutbeloppet av <span class="math inline">\(t\)</span> är stort tyder det på att H0 inte stämmer. P-värdet defineras som sannolikheten att få ett resultat som är “minst lika extremt” som det observerade, om H0 är sann. I vårt exempel betyder “minst lika extremt” att absolutbeloppet av den standardiserade differensen <span class="math inline">\(t = \frac{\bar{x} - 4000}{s / \sqrt{n}}\)</span> är större eller lika med absolutebeloppet av <span class="math inline">\(t = -2.662\)</span>, t-värdet som vi beräknar från data. Därför beräknar vi p-värdet som <span class="math display">\[\begin{eqnarray}
P\left( \left| \frac{\bar{x} - 3800}{s / \sqrt{n}} \right| \geq \left| -2.662 \right| \right) &amp; = &amp; P\left( \frac{\bar{x} - 3800}{s / \sqrt{n}} \leq -2.662 \right) + P\left( \frac{\bar{x} - 3800}{s / \sqrt{n}} \geq 2.662 \right)
\end{eqnarray}\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(<span class="at">q =</span> <span class="sc">-</span><span class="fl">2.662</span>, <span class="at">df =</span> <span class="dv">151</span> <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="at">q =</span> <span class="fl">2.662</span>, <span class="at">df =</span> <span class="dv">151</span> <span class="sc">-</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.008614753</code></pre>
</div>
</div>
<p>P-värdet avviker lite eftersom R använder fler decimaler för <span class="math inline">\(t\)</span>.</p>
<p>Jag kan rita täthetsfunktionen av t-fördelningen. P-värdet är egentligen den röda ytan under kurvan. Den blåa ytan motsvarar en “normal” standardiserade differens.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Statistik_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Från resultatet av <code>t.test()</code> står det att “95 percent confidence interval: 3626.926, 3774.398”. Det betyder att <span class="math inline">\(95\%\)</span> konfidensintervallet för medelviken <span class="math inline">\(\mu\)</span> är <span class="math inline">\(3626.926 &lt; \mu &lt; 3774.398\)</span>. Nullhypotesen är H0: <span class="math inline">\(\mu = 3800\)</span>. Om sådan <span class="math inline">\(3800\)</span> ingår i konfidensintevallet tyder på att H0 stämmer vid 5% signifikansnivå. Annars förkastar vi H0.</p>
<p>Vi kan även ser resultatet “sample estimates: mean of x 3700.662” från <code>t.test()</code>. Det betyder medelvärdet av våra data är 3700.662:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(vikt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3700.662</code></pre>
</div>
</div>
<p>Du får inte jämföra medelvärdet med konfidensintervallet för att bestämma om H0 stämmer. Värför det? Stickprovs medelvärde ligger alltid i konfidensintervallet! För att testa H0 använder vi det antagna värdet i H0, dvs 3800 i vårt exempel.</p>
</section>
<section id="h0-mu-leq-3800-textgram-mot-h1-mu-3800-textgram" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="h0-mu-leq-3800-textgram-mot-h1-mu-3800-textgram"><span class="header-section-number">2.2</span> H0: <span class="math inline">\(\mu \leq 3800 \text{gram}\)</span> mot H1: <span class="math inline">\(\mu &gt; 3800 \text{gram}\)</span></h2>
<p>Nu ändrar vi H0 till ensidighypotesen H0: <span class="math inline">\(\mu \leq 3800 \text{gram}\)</span>. Den standardiserade differensen mellan medelvikt och 3800 gram är forfarande <span class="math display">\[\begin{eqnarray}
t &amp; = &amp; \frac{\bar{x} - 3800}{s / \sqrt{n}}.
\end{eqnarray}\]</span></p>
<ul>
<li>Om <span class="math inline">\(t\)</span> är mycket större än 0 innebär att vår data tyder på att medelvikten är större än 3800, den antagna värdet i H0.</li>
<li>Om <span class="math inline">\(t\)</span> är mycket mindre än 0 innebär att vår data tyder på att medelvikten är mindre än 3800.</li>
</ul>
<p>När vi använder <code>t.test()</code> för att testa H0 mot H1 ovan får vi resultatet</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(vikt, <span class="at">mu =</span> <span class="dv">3800</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  vikt
t = -2.662, df = 150, p-value = 0.9957
alternative hypothesis: true mean is greater than 3800
95 percent confidence interval:
 3638.899      Inf
sample estimates:
mean of x 
 3700.662 </code></pre>
</div>
</div>
<p><span class="math inline">\(100(1 - \alpha)%\)</span> av alla studier skulle ge <span class="math inline">\(t &lt; t_{\alpha}^{(n-1)}\)</span> om vi kan upprepa samma studie många gånger. I vårt exempel är frihetsgraderna 150 (eftersom vi har <span class="math inline">\(151\)</span> observationer) och <span class="math inline">\(t_{\alpha}^{(n-1)} = 1.655076\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="at">p =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.05</span>, <span class="at">df =</span> <span class="dv">151</span> <span class="sc">-</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.655076</code></pre>
</div>
</div>
<p>Det innebär att ett t-värde som ligger mellan <span class="math inline">\(-Inf\)</span> och <span class="math inline">\(1.655076\)</span> anses vara helt “normalt” om H0 är sann. Om t-värdet ligger utanför <span class="math inline">\((-Inf, 1.655076)\)</span> anses våra data “konstiga” under H0. Det vill säga, om <span class="math inline">\(t\)</span> är stort tyder det på att H0 inte stämmer. I vårt exempel betyder “minst lika extremt” att den standardiserade differensen <span class="math inline">\(t = \frac{\bar{x} - 4000}{s / \sqrt{n}}\)</span> är större eller lika med <span class="math inline">\(t = -2.662\)</span>, t-värdet som vi beräknar från data. Därför beräknar vi p-värdet som <span class="math display">\[\begin{eqnarray}
P\left( \frac{\bar{x} - 3800}{s / \sqrt{n}} \geq -2.662 \right) &amp;
\end{eqnarray}\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="at">q =</span> <span class="sc">-</span><span class="fl">2.662</span>, <span class="at">df =</span> <span class="dv">151</span> <span class="sc">-</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9956926</code></pre>
</div>
</div>
<p>P-värdet avviker lite eftersom R använder fler decimaler för <span class="math inline">\(t\)</span>.</p>
<p>Jag kan rita täthetsfunktionen av t-fördelningen. P-värdet är egentligen den röda ytan under kurvan. Den blåa ytan motsvarar en “normal” standardiserade differens.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Statistik_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Från resultatet av <code>t.test()</code> står det att “95 percent confidence interval: 3626.926, 3774.398”. Det betyder att <span class="math inline">\(95\%\)</span> konfidensintervallet för medelviken <span class="math inline">\(\mu\)</span> är <span class="math inline">\(3626.926 &lt; \mu &lt; 3774.398\)</span>. Nullhypotesen är H0: <span class="math inline">\(\mu = 3800\)</span>. Om sådan <span class="math inline">\(3800\)</span> ingår i konfidensintevallet tyder på att H0 stämmer vid 5% signifikansnivå. Annars förkastar vi H0.</p>
<p>Vi kan även ser resultatet “sample estimates: mean of x 3700.662” från <code>t.test()</code>. Det betyder medelvärdet av våra data är 3700.662:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(vikt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3700.662</code></pre>
</div>
</div>
<p>Du får inte jämföra medelvärdet med konfidensintervallet för att bestämma om H0 stämmer. Värför det? Stickprovs medelvärde ligger alltid i konfidensintervallet! För att testa H0 använder vi det antagna värdet i H0, dvs 3800 i vårt exempel.</p>
</section>
<section id="h0-mu-geq-3800-textgram-mot-h1-mu-3800-textgram" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="h0-mu-geq-3800-textgram-mot-h1-mu-3800-textgram"><span class="header-section-number">2.3</span> H0: <span class="math inline">\(\mu \geq 3800 \text{gram}\)</span> mot H1: <span class="math inline">\(\mu &lt; 3800 \text{gram}\)</span></h2>
<p>Nu ändrar vi H0 till ensidighypotesen H0: <span class="math inline">\(\mu \geq 3800 \text{gram}\)</span>. Den standardiserade differensen mellan medelvikt och 3800 gram är forfarande <span class="math display">\[\begin{eqnarray}
t &amp; = &amp; \frac{\bar{x} - 3800}{s / \sqrt{n}}.
\end{eqnarray}\]</span></p>
<ul>
<li>Om <span class="math inline">\(t\)</span> är mycket större än 0 innebär att vår data tyder på att medelvikten är större än 3800, den antagna värdet i H0.</li>
<li>Om <span class="math inline">\(t\)</span> är mycket mindre än 0 innebär att vår data tyder på att medelvikten är mindre än 3800.</li>
</ul>
<p>När vi använder <code>t.test()</code> för att testa H0 mot H1 ovan får vi resultatet</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(vikt, <span class="at">mu =</span> <span class="dv">3800</span>, <span class="at">alternative =</span> <span class="st">"less"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  vikt
t = -2.662, df = 150, p-value = 0.004308
alternative hypothesis: true mean is less than 3800
95 percent confidence interval:
     -Inf 3762.426
sample estimates:
mean of x 
 3700.662 </code></pre>
</div>
</div>
<p><span class="math inline">\(100(1 - \alpha)%\)</span> av alla studier skulle ge <span class="math inline">\(t &gt; t_{1 - \alpha}^{(n-1)}\)</span> om vi kan upprepa samma studie många gånger. I vårt exempel är frihetsgraderna 150 (eftersom vi har <span class="math inline">\(151\)</span> observationer) och <span class="math inline">\(t_{1 - \alpha}^{(n-1)} = -1.655076\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.05</span>, <span class="at">df =</span> <span class="dv">151</span> <span class="sc">-</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.655076</code></pre>
</div>
</div>
<p>Det innebär att ett t-värde som ligger mellan <span class="math inline">\(-1.655076\)</span> och Inf anses vara helt “normalt” om H0 är sann. Om t-värdet ligger utanför <span class="math inline">\((-1.655076, Inf)\)</span> anses våra data “konstiga” under H0. Det vill säga, om <span class="math inline">\(t\)</span> är stort tyder det på att H0 inte stämmer. I vårt exempel betyder “minst lika extremt” att den standardiserade differensen <span class="math inline">\(t = \frac{\bar{x} - 4000}{s / \sqrt{n}}\)</span> är större eller lika med <span class="math inline">\(t = -2.662\)</span>, t-värdet som vi beräknar från data. Därför beräknar vi p-värdet som <span class="math display">\[\begin{eqnarray}
P\left( \frac{\bar{x} - 3800}{s / \sqrt{n}} \geq -2.662 \right) &amp;
\end{eqnarray}\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(<span class="at">q =</span> <span class="sc">-</span><span class="fl">2.662</span>, <span class="at">df =</span> <span class="dv">151</span> <span class="sc">-</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.004307377</code></pre>
</div>
</div>
<p>P-värdet avviker lite eftersom R använder fler decimaler för <span class="math inline">\(t\)</span>.</p>
<p>Jag kan rita täthetsfunktionen av t-fördelningen. P-värdet är egentligen den röda ytan under kurvan. Den blåa ytan motsvarar en “normal” standardiserade differens.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Statistik_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Från resultatet av <code>t.test()</code> står det att “95 percent confidence interval: -Inf 3762.426”. Det betyder att <span class="math inline">\(95\%\)</span> konfidensintervallet för medelviken <span class="math inline">\(\mu\)</span> är <span class="math inline">\(\mu &lt; 3762.426\)</span>. Nullhypotesen är H0: <span class="math inline">\(\mu = 3800\)</span>. Om sådan <span class="math inline">\(3800\)</span> ingår i konfidensintevallet tyder på att H0 stämmer vid 5% signifikansnivå. Annars förkastar vi H0.</p>
<p>Vi kan även ser resultatet “sample estimates: mean of x 3700.662” från <code>t.test()</code>. Det betyder medelvärdet av våra data är 3700.662:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(vikt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3700.662</code></pre>
</div>
</div>
<p>Du får inte jämföra medelvärdet med konfidensintervallet för att bestämma om H0 stämmer. Värför det? Stickprovs medelvärde ligger alltid i konfidensintervallet! För att testa H0 använder vi det antagna värdet i H0, dvs 3800 i vårt exempel.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>